# Generated by Django 2.2.12 on 2022-02-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_nascimento',
            field=models.CharField(max_length=100),
        ),
    ]
