# Generated by Django 2.2.12 on 2022-02-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('value_product', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='cep',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_products',
            field=models.FloatField(),
        ),
    ]
