# Generated by Django 2.2.12 on 2022-02-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20220210_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
