# Generated by Django 2.2.12 on 2022-02-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_sales_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='name',
        ),
    ]
